services:
  nosql-db:
    image: mvertes/alpine-mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  auth:
    build:
      dockerfile: Dockerfile
      context: ./auth
    container_name: authentication
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/auth/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - ./auth/.env.docker
    # Add other configuration like volumes, networks, etc.

  course-management:
    build:
      dockerfile: Dockerfile
      context: ./course-management
    container_name: courses
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/course-management/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - ./course-management/.env.example.docker
    # Add other configuration like volumes, networks, etc.

  forum-service:
    build:
      dockerfile: Dockerfile
      context: ./forum-service
    container_name: forum
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/forum-service/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - ./forum-service/.env.example.docker

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    container_name: gateway
    ports:
      - "80:80"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/gateway/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - ./gateway/.env.docker
    # Add other configuration like volumes, networks, etc.
